### ISSUE TITLE
win

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#1353]
error collections. lol.

**Comment by hainm** [comment]
`Cannot export actionlist: symbol not defined`

```bash
C:\Miniconda3-x64\envs\py34\Scripts\gcc.exe -mdll -O -Wall -IC:\projects\pytraj\cpptraj\src -IC:\projects\pytraj\pytraj -IC:\Miniconda3-x64\envs\py34\include -IC:\Miniconda3-x64\envs\py34\include -c pytraj\analysis\c_action\actionlist.cpp -o build\temp.win-amd64-3.4\Release\pytraj\analysis\c_action\actionlist.o
pytraj\analysis\c_action\actionlist.cpp: In function 'PyTypeObject* __Pyx_ImportType(const char*, const char*, size_t, int)':
pytraj\analysis\c_action\actionlist.cpp:27835:53: warning: unknown conversion type character 'z' in format [-Wformat=]
             module_name, class_name, basicsize, size);
                                                     ^
pytraj\analysis\c_action\actionlist.cpp:27835:53: warning: unknown conversion type character 'z' in format [-Wformat=]
pytraj\analysis\c_action\actionlist.cpp:27835:53: warning: too many arguments for format [-Wformat-extra-args]
writing build\temp.win-amd64-3.4\Release\pytraj\analysis\c_action\actionlist.def
C:\Miniconda3-x64\envs\py34\Scripts\g++.exe -shared -s build\temp.win-amd64-3.4\Release\pytraj\analysis\c_action\actionlist.o build\temp.win-amd64-3.4\Release\pytraj\analysis\c_action\actionlist.def -LC:\projects\pytraj\cpptraj\lib -LC:\Miniconda3-x64\envs\py34\libs -LC:\Miniconda3-x64\envs\py34\PCbuild\amd64 -lcpptraj -lpython34 -lmsvcr100 -o build\lib.win-amd64-3.4\pytraj\analysis\c_action\actionlist.pyd
Cannot export PyInit_pytraj: symbol not defined
Cannot export actionlist: symbol not defined
Cannot export analysis: symbol not defined
Cannot export c_action: symbol not defined
collect2
```

**Comment by hainm** [comment]
- 
```bash
python -c "import pytraj"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pytraj/__init__.py", line 18, in <module>
    from .utils.misc import info
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pytraj/utils/misc.py", line 7, in <module>
    from pytraj.core.c_options import set_world_silent
  File "C:/msys64/mingw64/lib/python2.7/site-packages/pytraj/core/__init__.py", line 2, in <module>
    from .topology_objects import Atom, Residue, Molecule
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by hainm** [comment]
shoot, I need two libcpptraj: `cpptraj.lib` for compiler, `libcpptraj.lib` for DLL detection. lol.

**Comment by hainm** [comment]
dirty solution

- copy `libcpptraj.lib`, `cpptraj.lib` to `pytraj` folder in `PYTHONPATH`
- update run path in `pytraj's __init__.py`:
```python
if sys.platform.startswith('win'):
    os.environ['PATH'] = os.path.dirname(os.path.abspath(__file__)) + ';' + os.environ['PATH']
```

**Comment by hainm** [comment]
- compiled with mingw64 and run with anaconda
https://www.ibm.com/developerworks/community/blogs/jfp/entry/Installing_XGBoost_For_Anaconda_on_Windows?lang=en

**Comment by hainm** [comment]
giving up. Users should use bash on win 10.
