### ISSUE TITLE
TypeError: no default __reduce__ due to non-trivial __cinit__ with cython 0.26

### ISSUE THREAD

**Issue by hainm** [Amber-MD/pytraj#1421]
uhm, need to define it.

**Comment by hainm** [comment]
uhm, I can't seem to reproduce this. Happens randomly?
Note: We do add `'auto_pickle': False,` to `setup.py`

**Comment by krlitros87** [comment]
I don't know if I should open a new ticket, but Im having the same problem.
Some info:
I installed ambertools via conda as explained here: https://ambermd.org/GetAmber.php
I installed pytraj  pytraj==2.0.6.dev0 doing:
cd pytraj/
python setup.py install

Everything went well, without problems.

But when trying to run wathershell:
shell_anions = pt.pmap(pt.watershell, traj, solute_mask=' :1', solvent_mask=':Cl-', upper=10, image=False,n_cores=4)
I get the following error message:

Traceback (most recent call last):
  File "/store1/navarro/PpGLR1/CA/wider/300mV/1/parallel.py", line 108, in <module>
    main()
  File "/store1/navarro/PpGLR1/CA/wider/300mV/1/parallel.py", line 104, in main
    shell_anions = pt.pmap(pt.watershell, traj, solute_mask=' :1', solvent_mask=':Cl-', upper=10, image=False,n_cores=4)
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/site-packages/pytraj/parallel/multiprocess.py", line 229, in pmap
    return _pmap(func, traj, *args, **kwargs)
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/site-packages/pytraj/parallel/multiprocess.py", line 219, in _pmap
    data = p.map(pfuncs, [rank for rank in range(n_cores)])
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/multiprocessing/pool.py", line 540, in _handle_tasks
    put(task)
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/multiprocessing/connection.py", line 211, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/navarro/miniconda3/envs/AmberTools22/lib/python3.10/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "stringsource", line 2, in pytraj.trajectory.c_traj.c_trajectory.TrajectoryCpptraj.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__


I haven't found a way to solve this problem, so any help is more than welcome.
Thanks!

**Comment by hainm** [comment]
> I installed ambertools via conda as explained here: https://ambermd.org/GetAmber.php

hi @krlitros87: `pytraj` is already included in ambertools so you don't need to install another pytraj.

**Comment by krlitros87** [comment]
Hi @hainm Thanks for your quick reply. I didn't know that (I was following an old tutorial I guess). Anyway, I remove my previous env and did everything again (I didn't install pytraj twice now), but I'm getting the same error
