### ISSUE TITLE
Error when search for Hbonds

### ISSUE THREAD

**Issue by IsmaheneMesbah** [Amber-MD/pytraj#1574]
Hi,

I want to perform H bonds analysis, I am following the tutorial:

`
hbonds = pt.search_hbonds(pdb_file)
hbonds.values
`

I have the following error:

`Traceback (most recent call last):

  File "/Users/macbookair/smd_software/readGromacs.py", line 109, in <module>
    hbonds = pt.search_hbonds(pdb_file)

  File "/opt/anaconda3/lib/python3.8/site-packages/pytraj/utils/decorators.py", line 11, in inner
    return f(*args, **kwd)

  File "/opt/anaconda3/lib/python3.8/site-packages/pytraj/utils/get_common_objects.py", line 296, in inner
    kwargs['top'] = get_topology(traj, top)

  File "/opt/anaconda3/lib/python3.8/site-packages/pytraj/utils/get_common_objects.py", line 57, in get_topology
    return top_

UnboundLocalError: local variable 'top_' referenced before assignment`

**Comment by hainm** [comment]
Hi

traj = pt.load(pdb_file)
pt.search_hbonds(traj)

**Comment by IsmaheneMesbah** [comment]
Thank you very much.
