### ISSUE TITLE
iterload trajectories with one frame don't support negative indexing

### ISSUE THREAD

**Issue by tuckerburgin** [Amber-MD/pytraj#1579]
Very minor issue, but hopefully an easy fix.

If you load a trajectory consisting of a single frame with iterload and then try to index it from the right, it throws an error:

```
>>> traj = pytraj.iterload('test.nc', 'test.prmtop')
>>> traj
pytraj.TrajectoryIterator, 1 frames: 
Size: 0.001538 (GB)
<Topology: 68813 atoms, 15842 residues, 15400 mols, PBC with box type = ortho>
>>> traj[-1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pytraj/trajectory/c_traj/c_trajectory.pyx", line 376, in pytraj.trajectory.c_traj.c_trajectory.TrajectoryCpptraj.__getitem__
ValueError: index is out of range
```

The same thing works fine with in-memory loading:

```
>>> traj = pytraj.load('test.nc', 'test.prmtop')
>>> traj
pytraj.Trajectory, 1 frames: 
Size: 0.001538 (GB)
<Topology: 68813 atoms, 15842 residues, 15400 mols, PBC with box type = ortho>
>>> traj[-1]
<Frame with 68813 atoms>
```

Negative index values seem to work just fine on out-of-memory iterload objects with more than one frame.

**Comment by hainm** [comment]
Thanks @tuckerburgin for your report. Indeed, it's a bug.

**Comment by hainm** [comment]
Should be fixed in https://github.com/Amber-MD/pytraj/pull/1597. Thanks @tuckerburgin very much.
