### ISSUE TITLE
Cannot build pytraj

### ISSUE THREAD

**Issue by ursulap** [Amber-MD/pytraj#1618]
Hello, I am new to this and I have been scooting for solutions for a few days now. Since this query (#800) is nearly the same as my issue I would like to reopen it because  both ./cpptraj folder and libcpptraj are not there.... 

But let me start from the beginning: 
I am trying to install the MD program Amber22. I am at the 3rd step of the process,"make install" (the first is just "tar" two files, the second is "./run_cmake"). I get to 94% install and then it is derailed. The details of 94% and onwards are below....

before going to the full detailed output @ 94% and onwards, some additional information ... ....

The error at step 94% was related to "Building pytraj"... 
Hence I went to http://amber-md.github.io/pytraj/latest/installation.html#from-source-code-easy-way-linux-osx

I followed these steps:
git clone https://github.com/Amber-MD/pytraj
cd pytraj
python3 setup.py install  

On running the latter, the error was:
can not find libcpptraj in $CPPTRAJHOME/lib. You need to install ``libcpptraj`` manually

And here is where my query differs from #800, $CPPTRAJHOME/lib, ./cpptraj and libcpptraj are not there

So then I went to install cpptraj (following instructions in http://amber-md.github.io/pytraj/latest/installation.html#from-source-code-easy-way-linux-osx) :

git clone https://github.com/Amber-MD/cpptraj
cd cpptraj
bash configure -shared -openmp gnu

This last step gave me this error:

  Testing C++ compiler (OpenMP): 
Error: Test compile failed: clang++  -Wall -fopenmp -O3  -fPIC   -o testp testp.cpp  -L/opt/homebrew/opt/llvm/lib -fopenmp  
Error: Check the output below for error messages:
clang: error: unsupported option '-fopenmp'

The issue to me was the pointing to the C++/clang compiler
I have installed gcc, llvm, libomp and others.., like R and I removed anaconda since its gfortran path was conflicting with the brew installation...

In searching forums that discuss this error (clang: error: unsupported option '-fopenmp')I found that I too could not run a simple "hello world" c script; it would give me the same error.

The workaround came from this site: https://stackoverflow.com/questions/43555410/enable-openmp-support-in-clang-in-mac-os-x-sierra-mojave

The command that allowed me to run was:
/opt/homebrew/opt/llvm/bin/clang -fopenmp omp_hello.c

if I remove "/opt/homebrew/opt/llvm/bin/" before clan I get the "clang: error: unsupported option '-fopenmp'" error.
if I replace "/opt/homebrew/opt/llvm/bin/" with "/usr/bin/" I get the same error "clang: error: unsupported option '-fopenmp'" error.
"clang -Xpreprocesssor -fopenmp omp_hello.c -lomp" didn't work either giving the error "fatal error: 'omp.h' file not found" , which according to "https://www.positioniseverything.net/clang-error-unsupported-option-fopenmp/", if this happens "I should ask about this issue on the Homebrew forum" - instead I am here :-)

Obviously this "prefix" to clang so that I can compile is problematic since I am not sure how to include it in "bash configure -shared -openmp gnu" line I was trying to run. 

I have both .zshrc and .zshr, in my home directory, and they both include the following:
export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
export PATH="/usr/local/opt/llvm/bin:$PATH" 

My "echo $PATH" is:
/Applications/CMake.app/Contents/bin:/usr/local/opt/llvm/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Apple/usr/bin:/Applications/ATSAS/bin

Now I am done with my detour, below it the error in pytraj installation. Thank you so much in advance! 

[ 94%] Building pytraj native library
sys.argv ['setup.py', 'build', '--disable-openmp']
Original compiler envs
CXX = /usr/bin/clang++
CC = /usr/bin/clang
COMPILER = 
use_pip = False, cpptraj_home = 
compile_c_extension = True
2.0.6
use_prebuilt_cythonized_files =  False
pytraj is inside AMBERHOME
using environment: CC=/usr/bin/clang, CXX=/usr/bin/clang++
using CC=/usr/bin/clang, CXX=/usr/bin/clang++
Final compiler envs
CXX = /usr/bin/clang++
CC = /usr/bin/clang
COMPILER = 
Traceback (most recent call last):
  File "/Applications/Amber/amber22_src/AmberTools/src/pytraj/setup.py", line 171, in <module>
    prepare_env_for_osx()
  File "/Applications/Amber/amber22_src/AmberTools/src/pytraj/setup.py", line 165, in prepare_env_for_osx
    warnings.warn("darwin_major_to_osx_map needs to be updated! Report this issue if build fails.")
NameError: name 'warnings' is not defined
make[2]: *** [AmberTools/src/pytraj/CMakeFiles/python-build/pytraj-build.stamp] Error 1
make[1]: *** [AmberTools/src/pytraj/CMakeFiles/pytraj.dir/all] Error 2
make: *** [all] Error 2

**Comment by hainm** [comment]
hi @ursulap 
Please edit the `/Applications/Amber/amber22_src/AmberTools/src/pytraj/setup.py` to add `import warnings` at the top. Sorry.

**Comment by dacase** [comment]
On Sat, Dec 10, 2022, ursulap wrote:

>I am trying to install the MD program Amber22. I am at the 3rd step of the
>process,"make install" (the first is just "tar" two files, the second is
>"./run_cmake"). I get to 94% install and then it is derailed. The details
>of 94% and onwards are below....

Thanks for all the details (really!) but apoligies if I am getting things
confused.

>git clone https://github.com/Amber-MD/cpptraj
>cd cpptraj
>bash configure -shared -openmp gnu

Did you try leaving out the -openmp flag?  There are a very places where
cpptraj could benefit, but most users will never enounter them.  That should
keep the -fopenmp flag out of the picture.  (Caveat: I've never installed
pytraj from Github.

>
>[ 94%] Building pytraj native library
>  File "/Applications/Amber/amber22_src/AmberTools/src/pytraj/setup.py", line 165, in prepare_env_for_osx
>    warnings.warn("darwin_major_to_osx_map needs to be updated! Report this issue if build fails.")

Ah...what is your OSX version?  It's really bad (tm) that the pytraj setup
needs to know intimate details of what OSX version you have, and that this
needs to get updated every time Apple does something.  Do you by any chance
have OSX 13 (Ventura)?

...thanks...dac
