### ISSUE TITLE
Amber22 installation: "source /home/xxxx/amber22/amber.sh" and "make test.serial" errors

### ISSUE THREAD

**Issue by ursulap** [Amber-MD/pytraj#1619]
Hello!

I have a Mac OS 13 and I have now installed Amber22 (though step: "make install" - my previous post was #1618 - thanks for helping out there!). However in the testing step ("make test.serial") I got several errors and failures (as seen in the summary file) - here is the summary:
------------------------
finished serial test suite for AmberTools at Mon Dec 12 11:01:48 CST 2022.

    2396 file comparisons passed
       8 file comparisons failed (       1 of which can be ignored)
       4 tests experienced errors
-------------------------

I ran an additional test using this line suggested by Hai to someone else (I can't find the page where I read it!):
 
"python3 -c "import sander"

and the output was:
------------------------
Could not import the compiled Python-sander interface. Make sure you have the Python development libraries installed and that you have sourced amber.sh or amber.cshTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/Amber/amber22/lib/python3.9/site-packages/sander/__init__.py", line 14, in <module>
    from . import pysander as _pys
ImportError: cannot import name 'pysander' from partially initialized module 'sander' (most likely due to a circular import) (/Applications/Amber/amber22/lib/python3.9/site-packages/sander/__init__.py)
----------------------
So the first question I have is: did I misplace or mishandled the line: "source /Applications/Amber/amber22/amber.sh"? I just simply added this command line to my local .zshrc and .zshr files. They read like this now:
------
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
source /Applications/Amber/amber22/amber.sh
------
I closed terminal and then re-opened it....an re-ran the test ("python3 -c "import sander") and the error persisted.

Putting "source /Applications/Amber/amber22/amber.sh" may be indeed incorrect! Is so where should it go.

I also installed development tools for python ("python3 -m pip install python-dev-tools --user --upgrade") and repeated the test ("python3 -c "import sander") but it continues to give me the same errors. 

In the error a reference to "sanders" led me to trying to install Python-sander? =>  "pip3 install python-timbl" but that resulted in errors as well:
------------------------------
Collecting python-timbl
  Using cached python-timbl-2017.04.04.tar.gz (28 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/zb/nhjs5chd7s78xshs8z_9f0h00000gn/T/pip-install-w15h3tb6/python-timbl_8218218eec1d40278de43acf720d7707/setup.py", line 7, in <module>
          from itertools import ifilter
      ImportError: cannot import name 'ifilter' from 'itertools' (unknown location)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
-----------------------------------------

...so maybe this is not the way to go....

Attached the full log and diff -zipped- files from "make test.serial".

Thank you in advance again,

-ursula

[2022-12-12_10-28-41.log.zip](https://github.com/Amber-MD/pytraj/files/10221417/2022-12-12_10-28-41.log.zip)

[2022-12-12_10-28-41.log.zip](https://github.com/Amber-MD/pytraj/files/10221423/2022-12-12_10-28-41.log.zip))

**Comment by hainm** [comment]
Hi

Please repost your question to AMBER mailing list. This github repo has very low traffic.

**Comment by hainm** [comment]
http://ambermd.org/MailingLists.php

**Comment by ursulap** [comment]
Hi I have emailed 3 times to amber-subscribe@ambermd.org with the simple subject "amber" or "subscribe" or blank "" and that is it and I have not received any confirmation... hence I am not in the list yet and hence I can not post this issue. 
-ursula
ps. in the meantime I checked the archive and I didn't find the solution to the issue above.. Looking forward to being able to have amber properly running :)
-ursula

**Comment by hainm** [comment]
> Hi I have emailed 3 times to [amber-subscribe@ambermd.org](mailto:amber-subscribe@ambermd.org) with the simple subject "amber" or "subscribe" or blank "" and that is it and I have not received any confirmation... hence I am not in the list yet and hence I can not post this issue. -ursula ps. in the meantime I checked the archive and I didn't find the solution to the issue above.. Looking forward to being able to have amber properly running :) -ursula

hi @ursulap, I suggest to check your spam filter in your email. Unfortunately posting question here won't help since (again), it's for `pytraj` and this repo has very low traffic.
